version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: chess-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: chessdb
      POSTGRES_USER: chess
      POSTGRES_PASSWORD: chesspass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chess -d chessdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_IMPROVED_STORAGE: "True"  # Fixes permission issues
      PGADMIN_LISTEN_PORT: 80                  # Explicit internal port
    ports:
      - "8083:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin          # Persistent config storage
    depends_on:
      postgres:
        condition: service_healthy             # Wait for PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pgdata:
    driver: local
  pgadmin_data:
    driver: local